export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_ABOUT_ME = "AUTH_ABOUT_ME";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_PASSWORD_RESET = "AUTH_PASSWORD_RESET";
export const AUTH_PASSWORD_CHANGE = "AUTH_PASSWORD_CHANGE";
export const AUTH_PASSWORD_SET = "AUTH_PASSWORD_SET";
